version: '3.1'
services:
  itoken-config:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: 192.168.17.131:5000/itoken-config
    container_name: itoken-config
    ports:
      - 8888:8888
    networks:
      - cloud

networks:
  cloud:
    external:
      name: spring_cloud